name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install tensorflowjs ultralytics

      - name: Convert YOLOv8 Model
        run: python scripts/convert_model.py

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build static files
        run: |
          # Ensure the model is copied to the docs directory
          mkdir -p docs/model
          cp -r static/model/* docs/model/

          # Update the docs directory
          cp -r static/js/* docs/js/
          cp -r static/css/* docs/css/
          
          # Copy the docs directory to _site for deployment
          cp -r docs/* _site/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
